### ISSUE TITLE
Verify a signature for a given data

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/stellar_sdk#178]
### Is your feature request related to a problem? Please describe.

The [`Keypair.sign/2`](https://hexdocs.pm/stellar_sdk/Stellar.KeyPair.Spec.html#c:sign/2) function allows signing a binary payload given a KeyPair.

However, there is not a function that checks the signature validity.

### Describe the solution you'd like

To implement a `Keypair.valid_signature?/3` function to validate the data signature given a public key.

### Additional context

https://stellar.github.io/js-stellar-sdk/signing.js.html

**Comment by miguelnietoa** [comment]
This function is already available on the v0.8.0 🎉
