### ISSUE TITLE
Documentation examples need to be fixed

### ISSUE THREAD

**Issue by miguelnietoa** [kommitters/stellar_sdk#179]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description
It seems like the examples of the library documentation are wrong, I guess they are just outdated.

- https://hexdocs.pm/stellar_sdk/0.7.0/create_account.html
- https://hexdocs.pm/stellar_sdk/0.7.0/payments.html

### Current behavior

Running the examples, it raises an error due to clause matching error.

### Expected behavior

The examples should not throw any error. 

### Additional context

The function `Stellar.TxBuild.envelope/1` can return `{:ok, envelope()} | {:error, atom()}`, but the function `Stellar.Horizon.Transactions.create/1` accept just the `base64_envelope` not a tuple. 

```elixir
# 5. submit the transaction to Horizon
{:ok, tx} =
  source_account
  |> Stellar.TxBuild.new(sequence_number: sequence_number)
  |> Stellar.TxBuild.add_operation(operation)
  |> Stellar.TxBuild.sign(signature)
  |> Stellar.TxBuild.envelope()
  |> Stellar.Horizon.Transactions.create()
```

**Comment by juanhurtado10** [comment]
Changes will be released within v.0.8.0
