### ISSUE TITLE
Create security policy to repository

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/stellar_sdk#185]
### Is your feature request related to a problem? Please describe.

**Security policy not enabled.**
A SECURITY.md file can give users information about what constitutes a vulnerability and how to report one securely so that information about a bug is not publicly visible. Examples of secure reporting methods include using an issue tracker with private issue support, or encrypted email with a published key.

### Describe the solution you'd like

To fix this, add a SECURITY.md file that explains how to handle vulnerabilities found in your repository. Go to https://github.com/kommitters/stellar_sdk/security/policy to enable it.

### Additional context

For more information, see https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository.

**Comment by juanhurtado10** [comment]
The policy is now in compliance. Closing issue.
