### ISSUE TITLE
SetOptionsOp returns an error when setting a signer

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/stellar_sdk#217]
### Precheck

- [X] Do a quick search and make sure the bug has not been reported yet.
- [X] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [X] Finally, be nice and have fun!.

### Description

`SetOptionsOp` returns an error when setting a signer

### Environment

* Elixir & Erlang/OTP versions (elixir --version): OTP23, v.1.11.2
* Operating system: macOS

### Current behavior

```elixir
op = Stellar.TxBuild.SetOptions.new(
  signer: [ed25519: "GDPLQNBD5XXXXXXXXXXXXXXXXXXXXXXXXX", weight: 1]
)

{:error, [signer: :invalid_signer]}
```

### Expected behavior

Allow setting a signer for an account through the `SetOptionsOp`. 
There are multiple signer keys that need to be allowed `:ed25519 | :sha256_hash | :pre_auth_tx `

```elixir
op = Stellar.TxBuild.SetOptions.new(
  signer: [ed25519: "GDPLQNBD5XXXXXXXXXXXXXXXXXXXXXXXXX", weight: 1]
)

%Stellar.TxBuild.SetOptions{
  ....
  signer: %Stellar.TxBuild.Signer{
    signer_key: %Stellar.TxBuild.SignerKey{
      key: "GDPLQNBD5XXXXXXXXXXXXXXXXXXXXXXXXX",
      type: :ed25519
    },
    weight: %Stellar.TxBuild.Weight{value: 1}
  }
}
````

**Comment by miguelnietoa** [comment]
Bug fixed in version `0.9.3`. 👌🏻
