### ISSUE TITLE
Updating the SDKs to the stable Protocol 20 release

### ISSUE THREAD

**Issue by Shaptic** [kommitters/stellar_sdk#341]
SDKs need to be updated to adapt to breaking changes that have occurred since Preview 11 (i.e. the current testnet release candidate) coming to Protocol 20.

## Summary of Breaking Changes
This is likely irrelevant to SDK maintainers, but do note sandbox mode has been removed from the Soroban CLI (https://github.com/stellar/soroban-tools/issues/983).

### XDR
The XDR needs to be updated to https://github.com/stellar/stellar-xdr/commit/6a620d160aab22609c982d54578ff6a63bfcdc01. This includes a non-trivial list of breaking changes (mostly renames):
  - The `BumpFootprintExpirationOp` is now `ExtendFootprintTTLOp` and its `ledgersToExpire` field is now named `extendTo`, but it serves the same purpose.
  - `ContractExecutable.contractExecutableToken` is now `contractExecutableStellarAsset`
  - `SorobanTransactionData.refundableFee` is now `resourceFee`
  - This new fee encompasses the entirety of the Soroban-related resource fees. Note that this is distinct from the "network-inclusion" fee that you would set on your transaction
  - see https://github.com/stellar/js-stellar-base/pull/704 for an example migration

### RPC
 - The `getEvents` RPC endpoint structure has changed:
   * `value: { xdr: string }` is now just `value: string` (https://github.com/stellar/soroban-tools/pull/1015)
   * `contractId` will always be a contract strkey (`C...` format) if present (https://github.com/stellar/soroban-tools/issues/1007)
 - The `getLedgerEntries` RPC endpoint now includes expiration info (https://github.com/stellar/soroban-tools/pull/1010):
   * `expirationLedgerSeq` is a string-ified `uint32` present if the requested entries have expiration

**Comment by Ifropc** [comment]
@EdwinGuayacan FYI, in case you missed this ^
XDR and RPC are stable for protocol version 20, and we expect it to be ready for testnet release! (Unless there is a critical bug found)
It would be great if you could let me know some estimates on when you expect the SDK to be up to date with the protocol changes. Thank you!

**Comment by Shaptic** [comment]
There is an additional schema change: the getLedgerEntries RPC response will use liveUntilLedgerSeq rather than expirationLedgerSeq in the final build (ref: stellar/soroban-tools#1029)

**Comment by miguelnietoa** [comment]
The changes have been implemented and will be released once the next Soroban release comes out!

Here are the PRs where the changes have been applied:

- `stellar_base`: https://github.com/kommitters/stellar_base/pull/296
- `stellar_sdk`: https://github.com/kommitters/stellar_sdk/pull/343
- `soroban.ex`: https://github.com/kommitters/soroban.ex/pull/141


Thank you @Shaptic @Ifropc

**Comment by Ifropc** [comment]
Hi @miguelnietoa just a heads-up, new quickstart image has been released couple days ago `stellar/quickstart:soroban-dev` and is updated to match futurenet and has all the p20 stable versions
So it should be available to test against

**Comment by miguelnietoa** [comment]
Hi @Ifropc, We are about to start testing again and do release once we confirm everything is working well. 😉
Thank u!
